### ISSUE TITLE
How to make buttons redirect instead of opening new window?

### ISSUE THREAD

**Issue by ferittuncer** [vaakash/socializer#1]
How to make buttons redirect instead of opening new window?

**Comment by vaakash** [comment]
@ferittuncer If you are using JS, then it is defaulted to open links in new window.
You can change "_blank" to "_self" in https://github.com/vaakash/socializer/blob/aaa2396863c8b1f6263e035cf694c6b9569ce5c3/js/socializer.js#L181

**Comment by ferittuncer** [comment]
Well I guess then I have to fork and modify socializer, right?
